version: '3.8'

services:
  wrk1:
    build: ./wrk
    container_name: wrk1
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
  wrk2:
    build: ./wrk
    container_name: wrk2
    ports:
      - "8081:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
  wrk3:
    build: ./wrk
    container_name: wrk3
    ports:
      - "8082:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
  wrk4:
    build: ./wrk
    container_name: wrk4
    ports:
      - "8083:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
  wrk5:
    build: ./wrk
    container_name: wrk5
    ports:
      - "8084:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080


volumes:
  postgres_data: