version: '3.8'

services:
  postgres:
    image: postgres:18.1-alpine
    container_name: events-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: events
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d events"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: events-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=12345
      - DB_NAME=events
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      # - BASE_URL=http://localhost:8080
  worker:
    build: ./worker
    container_name: events-worker
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=12345
      - DB_NAME=events
      - SERVICE_INTERVAL=10
    restart: unless-stopped

volumes:
  postgres_data: